// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KDT.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArzeshAfzode")
                        .HasColumnType("int");

                    b.Property<int>("FiGhablArzeshAfzode")
                        .HasColumnType("int");

                    b.Property<int>("GheymatNahaei")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MabdaHaml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MablaghDaryafti")
                        .HasColumnType("int");

                    b.Property<int>("MeghdarBargiri")
                        .HasColumnType("int");

                    b.Property<string>("MojavezBargiri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameMahsol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSherkat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVasete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoeForosh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("St")
                        .HasColumnType("int");

                    b.Property<int>("Takhfif")
                        .HasColumnType("int");

                    b.Property<DateTime>("TarikhEtebar")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarikhSabt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarikhsodor")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tedad")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
